// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ServerErrorMsgRow, ServerErrorMsgRowT } from '../proto/server-error-msg-row.js';


export class ServerErrorMsg implements flatbuffers.IUnpackableObject<ServerErrorMsgT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerErrorMsg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRoot(bb:flatbuffers.ByteBuffer, obj?:ServerErrorMsg):ServerErrorMsg {
  return (obj || new ServerErrorMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRoot(bb:flatbuffers.ByteBuffer, obj?:ServerErrorMsg):ServerErrorMsg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerErrorMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rows(index: number, obj?:ServerErrorMsgRow):ServerErrorMsgRow|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ServerErrorMsgRow()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rowsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startServerErrorMsg(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRows(builder:flatbuffers.Builder, rowsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, rowsOffset, 0);
}

static createRowsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRowsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishServerErrorMsgBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedServerErrorMsgBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static create(builder:flatbuffers.Builder, rowsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServerErrorMsg.startServerErrorMsg(builder);
  ServerErrorMsg.addRows(builder, rowsOffset);
  return ServerErrorMsg.end(builder);
}

unpack?(): ServerErrorMsgT {
  return new ServerErrorMsgT(
    this.bb!.createObjList<ServerErrorMsgRow, ServerErrorMsgRowT>(this.rows.bind(this), this.rowsLength())
  );
}


unpackTo(_o: ServerErrorMsgT): void {
  _o.rows = this.bb!.createObjList<ServerErrorMsgRow, ServerErrorMsgRowT>(this.rows.bind(this), this.rowsLength());
}
}

export class ServerErrorMsgT implements flatbuffers.IGeneratedObject {
constructor(
  public rows: (ServerErrorMsgRowT)[] = []
){}


pack?(builder:flatbuffers.Builder): flatbuffers.Offset {
  const rows = ServerErrorMsg.createRowsVector(builder, builder.createObjectOffsetList(this.rows));

  return ServerErrorMsg.create(builder,
    rows
  );
}
}
