import { Color as Color_ } from './color';
import { MapXDataRow as MapXDataRow_, MapXDataRowT as MapXDataRowT_ } from './map-xdata-row';
import { MapXData as MapXData_, MapXDataT as MapXDataT_ } from './map-xdata';
import { RequestUserEnter as RequestUserEnter_, RequestUserEnterT as RequestUserEnterT_ } from './request-user-enter';
import { ResponseUserEnter as ResponseUserEnter_, ResponseUserEnterT as ResponseUserEnterT_ } from './response-user-enter';
import { ServerErrorMsgRow as ServerErrorMsgRow_, ServerErrorMsgRowT as ServerErrorMsgRowT_ } from './server-error-msg-row';
import { ServerErrorMsg as ServerErrorMsg_, ServerErrorMsgT as ServerErrorMsgT_ } from './server-error-msg';
import { ServerErrorType as ServerErrorType_ } from './server-error-type';
import { UserInfo as UserInfo_, UserInfoT as UserInfoT_ } from './user-info';
import { Vec3 as Vec3_, Vec3T as Vec3T_ } from './vec3';
export declare namespace proto {
    const Color: typeof Color_;
    type IColor = Color_;
    const MapXDataRow: typeof MapXDataRow_;
    type IMapXDataRow = MapXDataRow_;
    const MapXDataRowT: typeof MapXDataRowT_;
    type IMapXDataRowT = MapXDataRowT_;
    const MapXData: typeof MapXData_;
    type IMapXData = MapXData_;
    const MapXDataT: typeof MapXDataT_;
    type IMapXDataT = MapXDataT_;
    const RequestUserEnter: typeof RequestUserEnter_;
    type IRequestUserEnter = RequestUserEnter_;
    const RequestUserEnterT: typeof RequestUserEnterT_;
    type IRequestUserEnterT = RequestUserEnterT_;
    const ResponseUserEnter: typeof ResponseUserEnter_;
    type IResponseUserEnter = ResponseUserEnter_;
    const ResponseUserEnterT: typeof ResponseUserEnterT_;
    type IResponseUserEnterT = ResponseUserEnterT_;
    const ServerErrorMsgRow: typeof ServerErrorMsgRow_;
    type IServerErrorMsgRow = ServerErrorMsgRow_;
    const ServerErrorMsgRowT: typeof ServerErrorMsgRowT_;
    type IServerErrorMsgRowT = ServerErrorMsgRowT_;
    const ServerErrorMsg: typeof ServerErrorMsg_;
    type IServerErrorMsg = ServerErrorMsg_;
    const ServerErrorMsgT: typeof ServerErrorMsgT_;
    type IServerErrorMsgT = ServerErrorMsgT_;
    const ServerErrorType: typeof ServerErrorType_;
    type IServerErrorType = ServerErrorType_;
    const UserInfo: typeof UserInfo_;
    type IUserInfo = UserInfo_;
    const UserInfoT: typeof UserInfoT_;
    type IUserInfoT = UserInfoT_;
    const Vec3: typeof Vec3_;
    type IVec3 = Vec3_;
    const Vec3T: typeof Vec3T_;
    type IVec3T = Vec3T_;
}
