// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
#![allow(warnings)]
pub mod proto {
  use super::*;
  mod color_generated;
  pub use self::color_generated::*;
  mod user_info_generated;
  pub use self::user_info_generated::*;
  mod request_user_enter_generated;
  pub use self::request_user_enter_generated::*;
  mod response_user_enter_generated;
  pub use self::response_user_enter_generated::*;
  mod request_user_hello_generated;
  pub use self::request_user_hello_generated::*;
  mod response_user_hello_generated;
  pub use self::response_user_hello_generated::*;
  mod vec_3_generated;
  pub use self::vec_3_generated::*;
  mod map_xdata_row_generated;
  pub use self::map_xdata_row_generated::*;
  mod map_xdata_generated;
  pub use self::map_xdata_generated::*;
  mod server_error_type_generated;
  pub use self::server_error_type_generated::*;
  mod server_error_msg_row_generated;
  pub use self::server_error_msg_row_generated::*;
  mod server_error_msg_generated;
  pub use self::server_error_msg_generated::*;
  mod user_exp_row_generated;
  pub use self::user_exp_row_generated::*;
  mod user_exp_generated;
  pub use self::user_exp_generated::*;
} // proto