FROM rust:1.76.0-alpine3.18 as builder

RUN apk upgrade --no-cache \
    && apk add --no-cache ca-certificates pkgconfig openssl-dev libc-dev alpine-sdk openssl libgcc libstdc++

WORKDIR /usr/src/app
COPY . .
RUN RUSTFLAGS="-Ctarget-feature=-crt-static" cargo build --release -p server-http

FROM alpine:3.18

RUN apk add --no-cache libgcc
RUN mkdir -p /app
WORKDIR /app

COPY --from=builder /usr/src/app/target/release/server-http /app/server-http