//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::db_schema_ups::Entity as DbSchemaUps;
pub use super::login_history::Entity as LoginHistory;
pub use super::system_mail::Entity as SystemMail;
pub use super::user_info::Entity as UserInfo;
pub use super::user_login::Entity as UserLogin;
