//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "system_mail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub is_active: i32,
    pub title: String,
    pub content: String,
    pub active_time: i64,
    pub expire_time: i64,
    pub reward_types: Vec<i32>,
    pub reward_values: Vec<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
