// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

public enum Color : sbyte
{
  WHITE = 0,
  RED = 1,
  GREEN = 2,
  BLUE = 3,
};


}
