// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RequestUserEnter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static RequestUserEnter GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new RequestUserEnter()); }
  public static RequestUserEnter GetRoot(ByteBuffer _bb, RequestUserEnter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RequestUserEnter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Token { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTokenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTokenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTokenArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Proto.RequestUserEnter> Create(FlatBufferBuilder builder,
      StringOffset tokenOffset = default(StringOffset)) {
    builder.StartTable(1);
    RequestUserEnter.AddToken(builder, tokenOffset);
    return RequestUserEnter.End(builder);
  }

  public static void StartRequestUserEnter(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddToken(FlatBufferBuilder builder, StringOffset tokenOffset) { builder.AddOffset(0, tokenOffset.Value, 0); }
  public static Offset<Proto.RequestUserEnter> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.RequestUserEnter>(o);
  }
  public RequestUserEnterT UnPack() {
    var _o = new RequestUserEnterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RequestUserEnterT _o) {
    _o.Token = this.Token;
  }
  public static Offset<Proto.RequestUserEnter> Pack(FlatBufferBuilder builder, RequestUserEnterT _o) {
    if (_o == null) return default(Offset<Proto.RequestUserEnter>);
    var _token = _o.Token == null ? default(StringOffset) : builder.CreateString(_o.Token);
    return Create(
      builder,
      _token);
  }
}

public class RequestUserEnterT
{
  public string Token { get; set; }

  public RequestUserEnterT() {
    this.Token = null;
  }
}


static public class RequestUserEnterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Token*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
