// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResponseUserEnter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ResponseUserEnter GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new ResponseUserEnter()); }
  public static ResponseUserEnter GetRoot(ByteBuffer _bb, ResponseUserEnter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResponseUserEnter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Code { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Proto.UserInfo? User { get { int o = __p.__offset(6); return o != 0 ? (Proto.UserInfo?)(new Proto.UserInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Proto.ResponseUserEnter> Create(FlatBufferBuilder builder,
      int code = 0,
      Offset<Proto.UserInfo> userOffset = default(Offset<Proto.UserInfo>)) {
    builder.StartTable(2);
    ResponseUserEnter.AddUser(builder, userOffset);
    ResponseUserEnter.AddCode(builder, code);
    return ResponseUserEnter.End(builder);
  }

  public static void StartResponseUserEnter(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCode(FlatBufferBuilder builder, int code) { builder.AddInt(0, code, 0); }
  public static void AddUser(FlatBufferBuilder builder, Offset<Proto.UserInfo> userOffset) { builder.AddOffset(1, userOffset.Value, 0); }
  public static Offset<Proto.ResponseUserEnter> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ResponseUserEnter>(o);
  }
  public ResponseUserEnterT UnPack() {
    var _o = new ResponseUserEnterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ResponseUserEnterT _o) {
    _o.Code = this.Code;
    _o.User = this.User.HasValue ? this.User.Value.UnPack() : null;
  }
  public static Offset<Proto.ResponseUserEnter> Pack(FlatBufferBuilder builder, ResponseUserEnterT _o) {
    if (_o == null) return default(Offset<Proto.ResponseUserEnter>);
    var _user = _o.User == null ? default(Offset<Proto.UserInfo>) : Proto.UserInfo.Pack(builder, _o.User);
    return Create(
      builder,
      _o.Code,
      _user);
  }
}

public class ResponseUserEnterT
{
  public int Code { get; set; }
  public Proto.UserInfoT User { get; set; }

  public ResponseUserEnterT() {
    this.Code = 0;
    this.User = null;
  }
}


static public class ResponseUserEnterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Code*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*User*/, Proto.UserInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
