// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerErrorMsg : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ServerErrorMsg GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new ServerErrorMsg()); }
  public static ServerErrorMsg GetRoot(ByteBuffer _bb, ServerErrorMsg obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyServerErrorMsg(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ServerErrorMsgVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerErrorMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Proto.ServerErrorMsgRow? Rows(int j) { int o = __p.__offset(4); return o != 0 ? (Proto.ServerErrorMsgRow?)(new Proto.ServerErrorMsgRow()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RowsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Proto.ServerErrorMsg> Create(FlatBufferBuilder builder,
      VectorOffset rowsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ServerErrorMsg.AddRows(builder, rowsOffset);
    return ServerErrorMsg.End(builder);
  }

  public static void StartServerErrorMsg(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRows(FlatBufferBuilder builder, VectorOffset rowsOffset) { builder.AddOffset(0, rowsOffset.Value, 0); }
  public static VectorOffset CreateRowsVector(FlatBufferBuilder builder, Offset<Proto.ServerErrorMsgRow>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRowsVectorBlock(FlatBufferBuilder builder, Offset<Proto.ServerErrorMsgRow>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRowsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Proto.ServerErrorMsgRow>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRowsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Proto.ServerErrorMsgRow>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRowsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Proto.ServerErrorMsg> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ServerErrorMsg>(o);
  }
  public static void Finish(FlatBufferBuilder builder, Offset<Proto.ServerErrorMsg> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedServerErrorMsgBuffer(FlatBufferBuilder builder, Offset<Proto.ServerErrorMsg> offset) { builder.FinishSizePrefixed(offset.Value); }
  public ServerErrorMsgT UnPack() {
    var _o = new ServerErrorMsgT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ServerErrorMsgT _o) {
    _o.Rows = new List<Proto.ServerErrorMsgRowT>();
    for (var _j = 0; _j < this.RowsLength; ++_j) {_o.Rows.Add(this.Rows(_j).HasValue ? this.Rows(_j).Value.UnPack() : null);}
  }
  public static Offset<Proto.ServerErrorMsg> Pack(FlatBufferBuilder builder, ServerErrorMsgT _o) {
    if (_o == null) return default(Offset<Proto.ServerErrorMsg>);
    var _rows = default(VectorOffset);
    if (_o.Rows != null) {
      var __rows = new Offset<Proto.ServerErrorMsgRow>[_o.Rows.Count];
      for (var _j = 0; _j < __rows.Length; ++_j) { __rows[_j] = Proto.ServerErrorMsgRow.Pack(builder, _o.Rows[_j]); }
      _rows = CreateRowsVector(builder, __rows);
    }
    return Create(
      builder,
      _rows);
  }
}

public class ServerErrorMsgT
{
  public List<Proto.ServerErrorMsgRowT> Rows { get; set; }

  public ServerErrorMsgT() {
    this.Rows = null;
  }
  public static ServerErrorMsgT DeserializeFromBinary(byte[] fbBuffer) {
    return ServerErrorMsg.GetRoot(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ServerErrorMsg.Finish(fbb, ServerErrorMsg.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


static public class ServerErrorMsgVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Rows*/, Proto.ServerErrorMsgRowVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
