// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RequestUserHello : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static RequestUserHello GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new RequestUserHello()); }
  public static RequestUserHello GetRoot(ByteBuffer _bb, RequestUserHello obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RequestUserHello __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRequestUserHello(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Proto.RequestUserHello> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.RequestUserHello>(o);
  }
  public RequestUserHelloT UnPack() {
    var _o = new RequestUserHelloT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RequestUserHelloT _o) {
  }
  public static Offset<Proto.RequestUserHello> Pack(FlatBufferBuilder builder, RequestUserHelloT _o) {
    if (_o == null) return default(Offset<Proto.RequestUserHello>);
    StartRequestUserHello(builder);
    return End(builder);
  }
}

public class RequestUserHelloT
{

  public RequestUserHelloT() {
  }
}


static public class RequestUserHelloVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
