// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ResponseUserHello : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ResponseUserHello GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new ResponseUserHello()); }
  public static ResponseUserHello GetRoot(ByteBuffer _bb, ResponseUserHello obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResponseUserHello __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Code { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Say { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSayBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSayBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSayArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Proto.ResponseUserHello> Create(FlatBufferBuilder builder,
      int code = 0,
      StringOffset sayOffset = default(StringOffset)) {
    builder.StartTable(2);
    ResponseUserHello.AddSay(builder, sayOffset);
    ResponseUserHello.AddCode(builder, code);
    return ResponseUserHello.End(builder);
  }

  public static void StartResponseUserHello(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCode(FlatBufferBuilder builder, int code) { builder.AddInt(0, code, 0); }
  public static void AddSay(FlatBufferBuilder builder, StringOffset sayOffset) { builder.AddOffset(1, sayOffset.Value, 0); }
  public static Offset<Proto.ResponseUserHello> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.ResponseUserHello>(o);
  }
  public ResponseUserHelloT UnPack() {
    var _o = new ResponseUserHelloT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ResponseUserHelloT _o) {
    _o.Code = this.Code;
    _o.Say = this.Say;
  }
  public static Offset<Proto.ResponseUserHello> Pack(FlatBufferBuilder builder, ResponseUserHelloT _o) {
    if (_o == null) return default(Offset<Proto.ResponseUserHello>);
    var _say = _o.Say == null ? default(StringOffset) : builder.CreateString(_o.Say);
    return Create(
      builder,
      _o.Code,
      _say);
  }
}

public class ResponseUserHelloT
{
  public int Code { get; set; }
  public string Say { get; set; }

  public ResponseUserHelloT() {
    this.Code = 0;
    this.Say = null;
  }
}


static public class ResponseUserHelloVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Code*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Say*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
