// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

public enum ServerErrorType : int
{
  ERR_SUCCESS = 0,
  ERR_FAILED = 1,
};


}
