// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UserExpRow : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static UserExpRow GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new UserExpRow()); }
  public static UserExpRow GetRoot(ByteBuffer _bb, UserExpRow obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UserExpRow __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Level { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long Exp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long ExpTotal { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Proto.UserExpRow> Create(FlatBufferBuilder builder,
      int level = 0,
      long exp = 0,
      long exp_total = 0) {
    builder.StartTable(3);
    UserExpRow.AddExpTotal(builder, exp_total);
    UserExpRow.AddExp(builder, exp);
    UserExpRow.AddLevel(builder, level);
    return UserExpRow.End(builder);
  }

  public static void StartUserExpRow(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(0, level, 0); }
  public static void AddExp(FlatBufferBuilder builder, long exp) { builder.AddLong(1, exp, 0); }
  public static void AddExpTotal(FlatBufferBuilder builder, long expTotal) { builder.AddLong(2, expTotal, 0); }
  public static Offset<Proto.UserExpRow> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Proto.UserExpRow>(o);
  }
  public UserExpRowT UnPack() {
    var _o = new UserExpRowT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(UserExpRowT _o) {
    _o.Level = this.Level;
    _o.Exp = this.Exp;
    _o.ExpTotal = this.ExpTotal;
  }
  public static Offset<Proto.UserExpRow> Pack(FlatBufferBuilder builder, UserExpRowT _o) {
    if (_o == null) return default(Offset<Proto.UserExpRow>);
    return Create(
      builder,
      _o.Level,
      _o.Exp,
      _o.ExpTotal);
  }
}

public class UserExpRowT
{
  public int Level { get; set; }
  public long Exp { get; set; }
  public long ExpTotal { get; set; }

  public UserExpRowT() {
    this.Level = 0;
    this.Exp = 0;
    this.ExpTotal = 0;
  }
}


static public class UserExpRowVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Exp*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*ExpTotal*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
