#!/usr/bin/env bash

unameOut="$(uname -s)"
case "${unameOut}" in
Linux*) machine="-linux" ;;
Darwin*) machine="-darwin-intel" ;;
CYGWIN*) machine=".exe" ;;
MINGW*) machine=".exe" ;;
*) machine="UNKNOWN:${unameOut}" ;;
esac

# shell get this file path
# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself

CWD=$(pwd)

SOURCE=${BASH_SOURCE[0]}
# echo $SOURCE
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)

EXE_PATH=$DIR/flatc$machine

cd $CWD

echo "flatc path: $EXE_PATH"
echo "current working directory: $CWD"
echo ""
echo "executing: $EXE_PATH $@"

$EXE_PATH $@
