version: "3"
services:

  redis:
    container_name: "redis"
    image: redis:7.0.9-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/data:/data
      - type: bind
        source: ./redis/redis.conf
        target: /etc/redis/redis.conf
    logging:
      driver: "local"
      options:
          max-file: 5
          max-size: 10m

  postgresql:
    container_name: "postgresql"
    image: postgres:14.7-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    logging:
      driver: "local"
      options:
          max-file: 5
          max-size: 10m
          
  http-server:
    container_name: "http-server"
    image: server-http:master-a322e0d
    restart: always
    working_dir: /app
    env_file:
      - config.env
    command: /app/server-http
    depends_on:
      - redis
      - postgresql
    logging:
      driver: "local"
      options:
          max-file: 5
          max-size: 10m

  ws-server:
    container_name: "ws-server"
    image: server-ws:master-a322e0d
    volumes:
      - ./server-ws/configs:/app/configs
    restart: always
    working_dir: /app
    env_file:
      - config.env
    command: /app/server-ws
    depends_on:
      - redis
      - postgresql
    logging:
      driver: "local"
      options:
          max-file: 5
          max-size: 10m

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
    expose:
      - "8080"
      - "8081"
    restart: always
    depends_on:
      - http-server
      - ws-server
    logging:
      driver: "local"
      options:
          max-file: 5
          max-size: 10m
