// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum UserExpOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UserExp<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for UserExp<'a> {
  type Inner = UserExp<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> UserExp<'a> {
  pub const VT_ROWS: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.UserExp"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    UserExp { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UserExpArgs<'args>
  ) -> flatbuffers::WIPOffset<UserExp<'bldr>> {
    let mut builder = UserExpBuilder::new(_fbb);
    if let Some(x) = args.rows { builder.add_rows(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> UserExpT {
    let rows = self.rows().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    UserExpT {
      rows,
    }
  }

  #[inline]
  pub fn rows(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<UserExpRow<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<UserExpRow>>>>(UserExp::VT_ROWS, None)}
  }
}

impl flatbuffers::Verifiable for UserExp<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<UserExpRow>>>>("rows", Self::VT_ROWS, false)?
     .finish();
    Ok(())
  }
}
pub struct UserExpArgs<'a> {
    pub rows: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<UserExpRow<'a>>>>>,
}
impl<'a> Default for UserExpArgs<'a> {
  #[inline]
  fn default() -> Self {
    UserExpArgs {
      rows: None,
    }
  }
}

pub struct UserExpBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> UserExpBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_rows(&mut self, rows: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<UserExpRow<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(UserExp::VT_ROWS, rows);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> UserExpBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UserExpBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<UserExp<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for UserExp<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("UserExp");
      ds.field("rows", &self.rows());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct UserExpT {
  pub rows: Option<Vec<UserExpRowT>>,
}
impl Default for UserExpT {
  fn default() -> Self {
    Self {
      rows: None,
    }
  }
}
impl UserExpT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<UserExp<'b>> {
    let rows = self.rows.as_ref().map(|x|{
      let w: Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    UserExp::create(_fbb, &UserExpArgs{
      rows,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `UserExp`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_user_exp_unchecked`.
pub fn root_as_user_exp(buf: &[u8]) -> Result<UserExp, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<UserExp>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `UserExp` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_user_exp_unchecked`.
pub fn size_prefixed_root_as_user_exp(buf: &[u8]) -> Result<UserExp, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<UserExp>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `UserExp` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_user_exp_unchecked`.
pub fn root_as_user_exp_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<UserExp<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<UserExp<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `UserExp` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_user_exp_unchecked`.
pub fn size_prefixed_root_as_user_exp_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<UserExp<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<UserExp<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a UserExp and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `UserExp`.
pub unsafe fn root_as_user_exp_unchecked(buf: &[u8]) -> UserExp {
  flatbuffers::root_unchecked::<UserExp>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed UserExp and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `UserExp`.
pub unsafe fn size_prefixed_root_as_user_exp_unchecked(buf: &[u8]) -> UserExp {
  flatbuffers::size_prefixed_root_unchecked::<UserExp>(buf)
}
#[inline]
pub fn finish_user_exp_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<UserExp<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_user_exp_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<UserExp<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
