// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum UserInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct UserInfo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for UserInfo<'a> {
  type Inner = UserInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> UserInfo<'a> {
  pub const VT_USER_ID: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_LEVEL: flatbuffers::VOffsetT = 8;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.UserInfo"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    UserInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args UserInfoArgs<'args>
  ) -> flatbuffers::WIPOffset<UserInfo<'bldr>> {
    let mut builder = UserInfoBuilder::new(_fbb);
    builder.add_user_id(args.user_id);
    builder.add_level(args.level);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> UserInfoT {
    let user_id = self.user_id();
    let name = self.name().map(|x| {
      x.to_string()
    });
    let level = self.level();
    UserInfoT {
      user_id,
      name,
      level,
    }
  }

  #[inline]
  pub fn user_id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(UserInfo::VT_USER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(UserInfo::VT_NAME, None)}
  }
  #[inline]
  pub fn level(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(UserInfo::VT_LEVEL, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for UserInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("user_id", Self::VT_USER_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<i32>("level", Self::VT_LEVEL, false)?
     .finish();
    Ok(())
  }
}
pub struct UserInfoArgs<'a> {
    pub user_id: i64,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub level: i32,
}
impl<'a> Default for UserInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    UserInfoArgs {
      user_id: 0,
      name: None,
      level: 0,
    }
  }
}

pub struct UserInfoBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> UserInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_user_id(&mut self, user_id: i64) {
    self.fbb_.push_slot::<i64>(UserInfo::VT_USER_ID, user_id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(UserInfo::VT_NAME, name);
  }
  #[inline]
  pub fn add_level(&mut self, level: i32) {
    self.fbb_.push_slot::<i32>(UserInfo::VT_LEVEL, level, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> UserInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    UserInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<UserInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for UserInfo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("UserInfo");
      ds.field("user_id", &self.user_id());
      ds.field("name", &self.name());
      ds.field("level", &self.level());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct UserInfoT {
  pub user_id: i64,
  pub name: Option<String>,
  pub level: i32,
}
impl Default for UserInfoT {
  fn default() -> Self {
    Self {
      user_id: 0,
      name: None,
      level: 0,
    }
  }
}
impl UserInfoT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<UserInfo<'b>> {
    let user_id = self.user_id;
    let name = self.name.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let level = self.level;
    UserInfo::create(_fbb, &UserInfoArgs{
      user_id,
      name,
      level,
    })
  }
}
