// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum RequestUserEnterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RequestUserEnter<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RequestUserEnter<'a> {
  type Inner = RequestUserEnter<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RequestUserEnter<'a> {
  pub const VT_TOKEN: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Proto.RequestUserEnter"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RequestUserEnter { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RequestUserEnterArgs<'args>
  ) -> flatbuffers::WIPOffset<RequestUserEnter<'bldr>> {
    let mut builder = RequestUserEnterBuilder::new(_fbb);
    if let Some(x) = args.token { builder.add_token(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> RequestUserEnterT {
    let token = self.token().map(|x| {
      x.to_string()
    });
    RequestUserEnterT {
      token,
    }
  }

  #[inline]
  pub fn token(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RequestUserEnter::VT_TOKEN, None)}
  }
}

impl flatbuffers::Verifiable for RequestUserEnter<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("token", Self::VT_TOKEN, false)?
     .finish();
    Ok(())
  }
}
pub struct RequestUserEnterArgs<'a> {
    pub token: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for RequestUserEnterArgs<'a> {
  #[inline]
  fn default() -> Self {
    RequestUserEnterArgs {
      token: None,
    }
  }
}

pub struct RequestUserEnterBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RequestUserEnterBuilder<'a, 'b> {
  #[inline]
  pub fn add_token(&mut self, token: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RequestUserEnter::VT_TOKEN, token);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RequestUserEnterBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RequestUserEnterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RequestUserEnter<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RequestUserEnter<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RequestUserEnter");
      ds.field("token", &self.token());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct RequestUserEnterT {
  pub token: Option<String>,
}
impl Default for RequestUserEnterT {
  fn default() -> Self {
    Self {
      token: None,
    }
  }
}
impl RequestUserEnterT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<RequestUserEnter<'b>> {
    let token = self.token.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    RequestUserEnter::create(_fbb, &RequestUserEnterArgs{
      token,
    })
  }
}
