// This file is auto-generated by tools/wrap-index.js

import { Bar as Bar_, BarT as BarT_,  } from './bar';
import { Color as Color_,  } from './color';
import { Foo as Foo_, FooT as FooT_,  } from './foo';
import { MapXDataRow as MapXDataRow_, MapXDataRowT as MapXDataRowT_,  } from './map-xdata-row';
import { MapXData as MapXData_, MapXDataT as MapXDataT_,  } from './map-xdata';
import { Vec3 as Vec3_, Vec3T as Vec3T_,  } from './vec3';
export namespace proto {
export const Bar = Bar_;
export type IBar = Bar_;
export const BarT = BarT_;
export type IBarT = BarT_;
export const Color = Color_;
export type IColor = Color_;
export const Foo = Foo_;
export type IFoo = Foo_;
export const FooT = FooT_;
export type IFooT = FooT_;
export const MapXDataRow = MapXDataRow_;
export type IMapXDataRow = MapXDataRow_;
export const MapXDataRowT = MapXDataRowT_;
export type IMapXDataRowT = MapXDataRowT_;
export const MapXData = MapXData_;
export type IMapXData = MapXData_;
export const MapXDataT = MapXDataT_;
export type IMapXDataT = MapXDataT_;
export const Vec3 = Vec3_;
export type IVec3 = Vec3_;
export const Vec3T = Vec3T_;
export type IVec3T = Vec3T_;
}
