//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::db_schema_ups::Entity as DbSchemaUps;
pub use super::login_history::Entity as LoginHistory;
pub use super::user::Entity as User;
pub use super::user_info::Entity as UserInfo;
